version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pwd
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - python -m unittest discover tests

