AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  validador_csv

  Sample SAM Template for validador_csv

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ValidadorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: validador/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies: [AmazonDynamoDBFullAccess,AmazonS3FullAccess]
      MemorySize: 256
      Timeout: 900
      Events:
        Validador:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /validador
            Method: post
      

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ValidadorApi:
    Description: "API Gateway endpoint URL for Prod stage for Vaidador function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ValidadorFunction:
    Description: "Validador Lambda Function ARN"
    Value: !GetAtt ValidadorFunction.Arn
  ValidadorFunctionIamRole:
    Description: "Implicit IAM Role created for Validador function"
    Value: !GetAtt ValidadorFunctionRole.Arn
